Repository octokit/plugin-rest-endpoint-methods.js, pull requests merged in 2023-06, with the labels that each got.

#644 fix(build): switch to esbuild and tsc instead of pika
  package-lock.json
  package.json
  scripts/build.mjs
  src/endpoints-to-methods.ts
  src/generated/endpoints.ts
  src/generated/method-types.ts
  src/generated/parameters-and-response-types.ts
  src/index.ts
  src/types.ts
  test/rest-endpoint-methods.test.ts
  test/tsconfig.test.json
  test/typescript.test.ts
  tsconfig.json
Labels: Type: Maintenance

#637 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package.json
  scripts/build.mjs
Labels: Type: Breaking change, Type: Maintenance

#622 fix(performance): pre-compute and lazily initialize endpoint methods
  src/endpoints-to-methods.ts
  src/index.ts
Labels: Type: Feature

#653 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation

#654 fix(deps): upgrade Octokit deps
  package-lock.json
  package.json
Labels: Type: Maintenance
